# Generated by Django 3.2.6 on 2021-10-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('sugestao', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_trajeto', models.CharField(max_length=100)),
                ('saida_garagem', models.CharField(choices=[('M', '6:30'), ('T', '12:00'), ('N', '18:30')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto_Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trajeto.bairro')),
                ('trajeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trajeto.trajeto')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trajeto.veiculo')),
            ],
            options={
                'unique_together': {('trajeto', 'bairro', 'veiculo')},
            },
        ),
    ]
