# Generated by Django 3.2.6 on 2021-09-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trajeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='sugestao',
            field=models.TextField(max_length=250),
        ),
    ]
