# Generated by Django 3.1.7 on 2021-09-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_trajeto', '0002_auto_20210920_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bairro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida_garagem', models.CharField(choices=[('M', '6:30'), ('T', '12:00'), ('N', '18:30')], max_length=1)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trajeto.bairro')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trajeto.veiculo')),
            ],
            options={
                'unique_together': {('bairro', 'veiculo', 'saida_garagem')},
            },
        ),
    ]
