# Generated by Django 3.2.6 on 2021-11-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trajeto', '0002_alter_bairro_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_transporte',
            field=models.IntegerField(default=1),
        ),
    ]
