# Generated by Django 3.2.13 on 2022-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trajeto', '0004_alter_veiculo_tipo_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('des', models.CharField(max_length=150)),
                ('hr', models.CharField(max_length=2)),
                ('mn', models.CharField(max_length=2)),
            ],
            options={
                'unique_together': {('lat', 'lon')},
            },
        ),
    ]
